-- Phase 50 — Auto-grant beta tester title to the first 30 app users after reset

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS beta_tester_title BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.profiles
ADD COLUMN IF NOT EXISTS beta_tester_title_granted_at TIMESTAMPTZ NULL;

CREATE TABLE IF NOT EXISTS public.beta_tester_title_grants (
    user_id UUID PRIMARY KEY,
    grant_number INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE,
    granted_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE OR REPLACE FUNCTION public.assign_beta_tester_title()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_beta_tester_count INTEGER;
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('public.profiles.beta_tester_title'));

    IF EXISTS (
        SELECT 1
        FROM public.beta_tester_title_grants
        WHERE user_id = NEW.id
    ) THEN
        NEW.beta_tester_title := TRUE;
        NEW.beta_tester_title_granted_at := COALESCE(NEW.beta_tester_title_granted_at, NOW());
        RETURN NEW;
    END IF;

    SELECT COUNT(*)
    INTO v_beta_tester_count
    FROM public.beta_tester_title_grants;

    IF v_beta_tester_count < 30 THEN
        INSERT INTO public.beta_tester_title_grants (user_id)
        VALUES (NEW.id);

        NEW.beta_tester_title := TRUE;
        NEW.beta_tester_title_granted_at := COALESCE(NEW.beta_tester_title_granted_at, NOW());
    ELSE
        NEW.beta_tester_title := FALSE;
        NEW.beta_tester_title_granted_at := NULL;
    END IF;

    RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_assign_beta_tester_title ON public.profiles;
CREATE TRIGGER trg_assign_beta_tester_title
BEFORE INSERT ON public.profiles
FOR EACH ROW
EXECUTE FUNCTION public.assign_beta_tester_title();

WITH earliest_profiles AS (
    SELECT id
    FROM public.profiles
    ORDER BY created_at ASC, id ASC
    LIMIT 30
),
inserted_grants AS (
    INSERT INTO public.beta_tester_title_grants (user_id)
    SELECT id
    FROM earliest_profiles
    ON CONFLICT (user_id) DO NOTHING
    RETURNING user_id
)
UPDATE public.profiles AS p
SET
    beta_tester_title = p.id IN (SELECT user_id FROM public.beta_tester_title_grants),
    beta_tester_title_granted_at = CASE
        WHEN p.id IN (SELECT user_id FROM public.beta_tester_title_grants)
            THEN COALESCE(p.beta_tester_title_granted_at, NOW())
        ELSE NULL
    END;

ALTER TABLE public.beta_tester_title_grants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "No client access to beta tester grants" ON public.beta_tester_title_grants;

REVOKE ALL ON public.beta_tester_title_grants FROM PUBLIC, anon, authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.beta_tester_title_grants TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.beta_tester_title_grants_grant_number_seq TO service_role;

REVOKE ALL ON FUNCTION public.assign_beta_tester_title() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.assign_beta_tester_title() TO postgres, supabase_auth_admin, service_role;
